### ISSUE TITLE
Release Checklist v.1.2

### ISSUE THREAD

**Issue by yiwen-h** [The-Strategy-Unit/nhp_project_information#35]
We have three types of releases: major, minor and patch following semantic versioning. Major releases must meet criteria for patch, minor and major. Minor releases must meet criteria for patch and minor.

We:

-	name Git tags and release titles in the form 'v1.2.3'
-	typically use the 'generate release notes' button in GitHub to autofill the release description
-	add update notes to the 'model updates' page of the NHP model project information site
- communicate all changes to key stakeholders and end users via the Model Relationship Manager system.

# Patch

## Data
Patch releases should not involve changes to data.

## Inputs
- [x] Scenarios can be created from scratch
- [x] New scenarios can be created from existing
- [x] Existing scenarios can be edited
- [x] If text for inputs has been updated, also update project_information

## End-to-end test
Patch releases should not involve changes to end-to-end process.

## Model
- [X] Model can be run locally on synthetic data

## Outputs
- [x] Able to load and view results for a model run
- [x] Click on all tabs and check figures show on all tabs

# Minor
- [X] 100% test coverage for all repos
- [x] Update posted on project_information site

## Data
- [x] Has been copied to Azure into v.X.Y.Z 
- [x] Changes have been recorded in data log

## Inputs
- [x] GH Actions variables updated to vX.Y.Z 
- [x] New version number added to inputs selection app dropdown 
- [x] Start model run

## End-to-end test
- [x] Check model run submitted from inputs app completes and scenario results are viewable on Outputs

## Model
- [x] GH Actions variables updated to vX.Y.Z 
- [x] Run at least 2 random scenarios from previous release and check results are similar to previous release.

## Outputs
- [x] Download results of new model scenario in Excel format
